### ISSUE TITLE
Adding open source programs

### ISSUE THREAD

**Issue by vedprakashnautiyal** [Sriparno08/Start-Contributing#1]
I think adding some open source programs will also be great

For example - LFX Mentorship, MLH Fellowship, LFN Mentorship, GSOC, Hactoberfest, SWOC, JWOC, etc.

**Comment by Sriparno08** [comment]
Good idea, @vedprakashnautiyal. If you want to contribute, feel free to make a PR!

**Comment by vedprakashnautiyal** [comment]
Okay I'll see what all I can include
