### ISSUE TITLE
Add PR Template

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Start-Contributing#10]
This repository needs a PR template that will improve the quality of the PRs made by the contributors.

Suggestions:

1. Create a 'Description' header under which contributors will describe the changes made in the PR
2. Create a 'Category' header containing three checkboxes named 'Article', 'YouTube Video' and 'Open Source Program'
3. Created a 'Related Issue' header under which contributors will link their PR to the corresponding issue
4. Set the name of the template to PULL_REQUEST_TEMPLATE.md

**Comment by harsha-mangena** [comment]
Hi @Sriparno08, Can I pick this up?

**Comment by Sriparno08** [comment]
Absolutely, @harsha-mangena!

I'm assigning this to you.
