### ISSUE TITLE
Add 'Beginner-Friendly Repositories' Category

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Start-Contributing#17]
Add a 'Beginner-Friendly Repositories' category between 'Contributing to Open Source' and 'Open Source Programs'.

Also, add a bullet point containing a resource under the new category. Here are the details:

Name: MDN Web Docs
Link: https://github.com/mdn/content

It will look like this:

> ## 😇 Beginner-Friendly Repositories
>
> - [MDN Web Docs](https://github.com/mdn/content)

**Comment by ConstiCode** [comment]
Hi @Sriparno08 ! I tried my best to adress the issue. I created a new branch altered the README.md by adding the descibed category. I hope my workflow and my commit is correct. Alsways open for Feedback!
