### ISSUE TITLE
Add Description Under 'Open Source Programs'

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Start-Contributing#18]
We need to have a description under 'Open Source Programs' to introduce the topic to the readers.

Suggested Description:

> There are a lot of open source programs on the internet that allow you to contribute to open source projects.
>
> Here is a list of such initiatives that you can participate in and upskill yourself in open source contributions.

**Comment by SahajaThota** [comment]
Hello @Sriparno08  ,
I express my willingness to make a contribution to the open source programs. Kindly provide me with further details regarding the specific nature of the contribution you are seeking for.

Thanks in advance!

**Comment by Sriparno08** [comment]
Hey @SahajaThota, I've added the suggested description above.

You need to add that between the 'Open Source Programs' header and the bulleted list.

The markdown should look like this:

```
## 🏅 Open Source Programs

There are a lot of open source programs on the internet that allow you to contribute to open source projects.

Here is a list of such initiatives that you can participate in and upskill yourself in open source contributions.

- [MLH Fellowship](https://fellowship.mlh.io/)
```

**Comment by SahajaThota** [comment]
Thanks for the update @Sriparno08,

I have added the description to the readme.md file can you kindly check it and let me know if any changes needs to be done.

Thanks.
