### ISSUE TITLE
Add Description Under 'Beginner-Friendly Repositories'

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Start-Contributing#25]
We need to add a description under 'Beginner-Friendly Repositories' to introduce the section to the readers.

Suggested Description:

> There are many repositories that enable you to get started with open source by providing a number of beginner-friendly issues.
>
> Here are some of those repositories that will give you a head start in open source:

**Comment by khamkarsuraj** [comment]
Hello @Sriparno08,
Could you please assign me this task. I would like to work on this.
