### ISSUE TITLE
Change 'Description' in PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Start-Contributing#36]
## Category

- [x] Documentation
- [ ] Resource Addition

## Description

We need to change 'Description' in PULL_REQUEST_TEMPLATE.md by replacing the current markdown with the suggested markdown.

Current Markdown:

```
## Description
<!-- Please provide a summary of your changes. Include the motivation behind the changes and link to any relevant issues. This section should provide enough information for anyone reviewing your PR to understand what's being changed and why. -->

*Describe your changes here*
```

Suggested Markdown:

```
## Description

<!-- Describe the changes made in the PR -->
```

**Comment by Sriparno08** [comment]
Sure, @pradeepch2107.

Steps:

1. Go to .github/PULL_REQUEST_TEMPLATE.md
2. Find the markdown that matches with the one under 'Current Markdown' mentioned in this issue
3. Replace the markdown with the one under 'Suggested Markdown' mentioned in this issue

**Comment by pradeepch2107** [comment]
It asks me to describe your changes here? Whats that mean? What should i describe?

**Comment by Sriparno08** [comment]
Just describe your changes made in the PR. To be specific, you can write something like this:

> Changed the 'Description' section in PULL_REQUEST_TEMPLATE.md.

**Comment by pradeepch2107** [comment]
Ok

**Comment by Sriparno08** [comment]
Hey @pradeepch2107, are you still working on this issue?

**Comment by ruchit-t** [comment]
@Sriparno08 Can you please assign this to me?

**Comment by ruchit-t** [comment]
Hi @Sriparno08 
I made changes to the PULL_REQUEST_TEMPLATE.md.
Here is the PR number: #48
Please approve it if it is correct! Thanks

**Comment by Sriparno08** [comment]
Hey @pradeepch2107, since you haven't been able to respond, I'm assigning this issue to @ruchit-t.

If you want to contribute, go to the 'Issues' tab to take a look at the other open issues.
