### ISSUE TITLE
Add First Contributions

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Start-Contributing#41]
## Category

- [ ] Documentation
- [x] Resource Addition

## Description

We need to add First Contributions under 'Beginner-Friendly Repositories'.

Name: First Contributions
Link: https://github.com/firstcontributions/first-contributions

**Comment by Sriparno08** [comment]
Hey @ruchit-t, do you want to get assigned to this issue too?

**Comment by ruchit-t** [comment]
Yes, That'd be great!

**Comment by Sriparno08** [comment]
Hey @ruchit-t, since you haven't been able to respond, I am unassigning you from this issue as it will make the issue open to other contributors.

If you want to contribute, you can go to the 'Issues' tab and check the other open issues in there.
