### ISSUE TITLE
Add Docusaurus

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Start-Contributing#54]
## Category

- [ ] Documentation
- [x] Resource Addition

## Description

We need to add Docusaurus under 'Beginner-Friendly Repositories'.

Name: Docusaurus
Link: https://github.com/facebook/docusaurus

**Comment by skadogg** [comment]
I can help with this.

**Comment by Sriparno08** [comment]
Great, @skadogg!

I'm assigning it to you.
