### ISSUE TITLE
Merge Steps in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Start-Contributing#8]
Merge steps 7 and 8 in 'Making a Pull Request' section in CONTRIBUTING.md.

Current Version:

> **Step 7:** Add a resource to the `README.md` file
> **Step 8:** Stage changes:

Suggested Version:

> **Step 7:** Modify `README.md` and stage changes:

Also, modify the next step numbers to support the change.

**Comment by Tashuuuu** [comment]
I would like to work on this.
